// src/collections-manager/cm-utils.js
const path = require('path');

/**
 * Derives a sanitized collection name from a source URL or path.
 * @param {string} source - The source URL or local path.
 * @returns {string} A sanitized string suitable for use as a directory name.
 */
function deriveCollectionName(source) {
  if (!source || typeof source !== 'string') {
    return ''; // Or throw an error, depending on desired strictness
  }
  const baseName = path.basename(source);
  let sanitized = baseName.replace(/\.git$/, '');

  // Replace one or more non-alphanumeric (excluding hyphen/underscore) with a single hyphen.
  sanitized = sanitized.replace(/[^a-zA-Z0-9_-]+/g, '-');

  // Collapse any consecutive hyphens (e.g., "---" -> "-")
  sanitized = sanitized.replace(/-{2,}/g, '-');

  // Remove only leading hyphens, as per test expectations (e.g., '-my-repo' -> 'my-repo').
  // Trailing hyphens are preserved if they existed in the original sanitized baseName and not generated by replacement.
  sanitized = sanitized.replace(/^-+/, '');

  return sanitized;
}

/**
 * Converts a hyphenated string to PascalCase.
 * e.g., "my-plugin-name" -> "MyPluginName"
 * @param {string} str - The input string.
 * @returns {string} The PascalCase string.
 */
function toPascalCase(str) {
  if (!str) return '';
  return str.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join('');
}

/**
 * Validates the plugin name.
 * Allowed: letters, numbers, hyphens. Must start/end with letter/number.
 * @param {string} pluginName - The name of the plugin.
 * @returns {boolean} True if valid, false otherwise.
 */
function isValidPluginName(pluginName) {
    if (!pluginName || typeof pluginName !== 'string') {
        return false;
    }
    // Allows alphanumeric, and hyphens not at start/end. Does not allow underscore.
    const regex = /^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$/;
    return regex.test(pluginName);
}

module.exports = {
  deriveCollectionName,
  toPascalCase,
  isValidPluginName, // Export the new utility
};
